### ISSUE TITLE
pinscan usage

### ISSUE THREAD

**Issue by bonuzzz** [kuba2k2/libretuya#10]
On my motor switch I have two relays and three touch buttons. I found pins of relays, but I can't find pins of buttons.
I think in theory itis possible to find them, but I don't see anything in pinscan, when I push buttons

**Comment by kuba2k2** [comment]
Right, PinScan doesn't enable internal pull-up/pull-down when doing manual scan. 

If you verify that the button has no hardware pull (no resistor to GND or VCC) you can run manual scan, and apply voltage (0V or 3.3V) to the button terminal, to see which pin changes.
