### ISSUE TITLE
Cannot update the device post initial install

### ISSUE THREAD

**Issue by fokcuk** [kuba2k2/libretuya#108]
Hello
For some reason the update has stopped working. I changed the code, but even though it says it compiled and OTA pushed through ESPHome, the device is still not updated - old sensor names.

I tried deleting the device and recreating it in ESPHome, but its still the same thing - no update

**Comment by kuba2k2** [comment]
What version of libretuya and what chip are you using? What board name did you choose?

**Comment by fokcuk** [comment]
turned out to be a device specific issue - if you hold the button after powering it off and then plugging back in with button pressed, it will start to use firmware. So its loading it, but not using is for some reason.
Closing the issue

**Comment by kuba2k2** [comment]
This is very weird, can you tell me more about this device? Is it Realtek or Beken?

**Comment by fokcuk** [comment]
Beken

**Comment by kuba2k2** [comment]
Then it's not really possible to update depending on the button presses. The bootloader should update the firmware as soon as it receives it.
