### ISSUE TITLE
Can't compile in osX

### ISSUE THREAD

**Issue by dbuezas** [kuba2k2/libretuya#18]
## It shows:
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: .pioenvs/tuya-power-switch/libbk7231n_fixups.a the table of contents is empty (no object file members in the library define global symbols)

## workaround
1. go to `~/.platformio/platforms/libretuya/builder/main.py`,
2. uncomment     #RANLIB=prefix + "gcc-ranlib"

Now it works in osX

**Comment by kuba2k2** [comment]
Fixed in 24e4b0b37610f039c1d8b7e48f64fc7e57980af8.
