### ISSUE TITLE
Add RFIO pin for generic-rtl8710bx-4mb-980k

### ISSUE THREAD

**Issue by mihsu81** [kuba2k2/libretuya#43]
Hi @kuba2k2,

Please add the RFIO pin (Pin 9) present in the RTL8710BX (generic-rtl8710bx-4mb-980k). In my device EZVIZ T31 it is mapped to a physical button and was used by EZVIZ to trigger a reset of the SSID.
https://jlcpcb.com/partdetail/RealtekSemicon-RTL8710BX_A0CG/C398719

![RTL8710BX-A0-CG Realtek Semicon _ C398719](https://user-images.githubusercontent.com/40715497/202892169-3696d675-5cc7-44af-ad8b-ce068b22c4ea.png)

**Comment by kuba2k2** [comment]
RFIO is not a GPIO input/output. Are you absolutely sure this pin is mapped to a button?

**Comment by mihsu81** [comment]
It seemed to be. I've verified the continuity between that pin and Pin1 of the physical switch.

**Comment by kuba2k2** [comment]
Isn't that pin GND by any chance? RFIO may be closely wired to GND so your continuity tester may show it's connected.

**Comment by mihsu81** [comment]
You're absolutely right. I guess I'll have to do more tests to identify the switch. Thanks.
