### ISSUE TITLE
Use ESPHome port on HASS ESPhome docker container?

### ISSUE THREAD

**Issue by craigueh** [kuba2k2/libretuya#45]
I have ESPhome running as a docker container on HassOS via the Hass native addon.
Is there any way to use the libretuya/esphome fork with this installation? I have over 120 ESP devices in my ESPHome dashboard and don't really want to have to move everything to a separate ESPHome installation elsewhere.

Thanks.

**Comment by kuba2k2** [comment]
There's some work ongoing in #54. Closing this as duplicate.
