### ISSUE TITLE
I can't access web_server?

### ISSUE THREAD

**Issue by maxupunk** [kuba2k2/libretuya#47]
when it enters ap mode it delivers the ip class 192.168.4.x and I try to access it through the port http://192.168.4.1:80 and I have also used nmap to test the ports but I don't think so.
The question: is this a bug or the web server system hasn't been implemented yet or I don't know how to configure it?

Thank you in advance for your attention and for sharing the project, congratulations on your project.

**Comment by kuba2k2** [comment]
Are you running ESPHome or your custom firmware?

**Comment by maxupunk** [comment]
I did the procedure as it is in the document, I didn't even do a customization.
