### ISSUE TITLE
ESPHome-LibreTuya PWM

### ISSUE THREAD

**Issue by lewiatanx** [kuba2k2/libretuya#62]
Can and how can I use PWM control for the cb2s and others chip?
For esp8266 it is:
- platform: esp8266_pwm
  
How to do it in LibreTuya's ESPHome port?

**Comment by kuba2k2** [comment]
Use LEDC, just like on ESP32. Most stuff in ESPHome LibreTuya is used like on ESP32.

**Comment by lewiatanx** [comment]
Oh yes, I forgot that these processors should be treated similarly to esp32 😅 Thank you for the tip.  Thanks to 'Tuya CloudCutter', 'LibreTuya' and the port to ESPHome my RGBCCT bulbs, Aubess switches and other accessories already work stably on ESPHome in HA.  Great, great project 👍 I hope it will continue to be developed.

**Comment by kuba2k2** [comment]
It will indeed!
