### ISSUE TITLE
read/write data in flash memory

### ISSUE THREAD

**Issue by dinnaAPP** [kuba2k2/libretuya#90]
Hi, I need to write and read data and I understand that RTC memory cannot be used, therefore I must use flash memory. Could you give me an example of how to do it?
Basically I want to store wifi ssid and pass.
Regards.

**Comment by kuba2k2** [comment]
There's a Flash library:
https://docs.libretuya.ml/ltapi/class_flash_class/

And there's also FlashDB, which is used in ESPHome to store Key-Value preferences (which looks like a perfect fit for your use case):
https://armink.github.io/FlashDB/#/sample-kvdb-basic
https://github.com/kuba2k2/libretuya-esphome/blob/platform/libretuya/esphome/components/libretuya/preferences.cpp

**Comment by dinnaAPP** [comment]
Thanks! I'm going to check it

**Comment by dinnaAPP** [comment]
Hi kuba2k2, I am using FlashClass for reading/writing. I would need help with the offset, since I can read but when I write, the program freeze, I guess I am writing over the program.

**Comment by kuba2k2** [comment]
What CPU are you using?
Flash offset tables are in the docs. For example, for Realtek:
https://docs.libretuya.ml/boards/wr3/#flash-memory-map

**Comment by dinnaAPP** [comment]
BK7231N, I had not seen that info. Read/write tested, OK!, Thanks.
