### ISSUE TITLE
IMPORTANT: New project name

### ISSUE THREAD

**Issue by kuba2k2** [kuba2k2/libretuya#92]
The project name is about to be changed to something else, for a few reasons:
- to address any issues that may arise due to the possibility of "LibreTuya" name violating Tuya Inc.'s trademark rights. We don't want any legal trouble, nor to interfere with Tuya's marketing.
- the project is meant to support more than RTL8710BN/BK7231 - that means it will work with chips not necessarily developed/distributed by Tuya.

The rules are simple - it should be nice, have two words only: first word being `Libre`, second word starting with the letter T. Why? Because there's just *way too many* references and usages of "LT" in code, documentation, tools, etc. Also, *Libre* sounds cool.

We've had a discussion on our Discord server about name ideas. **You can vote under this post, by adding an appropriate reaction** (the emojis don't indicate any preference).

Emoji | Name | Comment
--|--|--
:+1: | LibreThings | It seems to relate to SmartThings, which may be confusing
:smile: | LibreTiny | "As in something that runs on small devices" sounds really cool
:tada: | LibreTurtle | "Turtles don't sue, and they're dope" idk, I kinda like this one
:heart: | LibreThink | 
:rocket: | LibreTech | 
:eyes: | LibreTinker |

If you have any good suggestions, feel free to post them in this thread, and I can add them to the list.

If you really need to, you can cast more than one vote. Thanks!

**Comment by kuba2k2** [comment]
After careful consideration, I'm pretty much convinced about using LibreTiny as the name, despite the voting showing otherwise. I'd like to be satisfied about the project, so that might ultimately be my choice. I'm sorry for any inconvenience caused by this.

**Comment by dbuezas** [comment]
LibreTiny is cool! 👍 
It is absolutely your choice, and a good idea to gather community opinions before deciding, regardless of your final pick

**Comment by heffneil** [comment]
I love Tinkerer so LibreTinker for me!

**Comment by agittins** [comment]
LibreTiny is a pretty solid choice, imo - it speaks to the smaller devices that these chips are most likely to be found in.

Another option might be LibreToyou (pronounced Libre To You) as a play on going from Tuya (to ya) to To You - however that might be a somewhat Australian-specific play on words :-)

Turtles are also dope, though.

**Comment by digiblur** [comment]
It's on the ForYuh network ;)

**Comment by hn** [comment]
LibreTino = Libre Tiny Arduino (compatible cores)

**Comment by marcusrbrown** [comment]
**LibreToys**

_Libre_ can be a synonym for _free_ (i.e., FLOSS, OSS, etc.). LibreToys = "the free(ing of) toys."

**Comment by Habbie** [comment]
LibrIOT / LibrioT? probably not better than some of the given options but wanted to share this thought anyway.

**Comment by fantasmisiciliani** [comment]
Why not LibreTuma? 
https://en.m.wikipedia.org/wiki/Tuma_(cheese)
Yummy!😋 🙈

**Comment by jbornema** [comment]
I bring in another one:
**LibreSmart**

**Comment by descipher** [comment]
LibreType could be an option. Type cast away .. lol

**Comment by kuba2k2** [comment]
Looking at the results of the poll, seems like LibreTiny is our winner :tada: 

Again, I apologize for my 2nd post in this thread, possibly causing any influence on your votes. I hope that the new name will meet everyone's expectations.

And huge thanks to @Chrille#2270 at Discord for originally suggesting this name!
