### ISSUE TITLE
Unable to Flash to Certain Modules

### ISSUE THREAD

**Issue by marcosrogers** [kuba2k2/libretuya#93]
I'm having an issue flashing certain modules, and it seems to be something in the compiled firmware that it's rejecting. It started happening to 5 devices at the same time. When I update OTA, there are no errors, but upon reboot, the devices still have the previous firmware. Four of these devices (by Sylvania, but cut manually because they couldn't use SmartLife) are identical to each other and nearly identical to four other bulbs (TreatLife SL10 v2)—both of these use WB8P and the same pin layout, but evidently there are some other differences at play.

Where it gets interesting is with the other device, a Merkury Innovations MI-BW942-999W. I installed LT-ESPHome to it more recently than the other bulbs, but it also stopped being able to update firmware when the other 4 bulbs did. Then I cut another BW942 bulb, installing OpenBeken to it as the first step. OpenBeken installed fine (v. 1.15.445), then I used its OTA option to try flashing ESPHome to it. It seemed to flash successfully, but when it restarted, it was still running OpenBeken. I tried again, same result. So I tried flashing a newer version of OpenBeken (1.15.483), which it flashed successfully. So that's what makes it seem like it's a code change that is making some devices refuse to update.

The compilation info for the last version of LT-ESPHome I was able to flash successfully on the 5 devices that have not updated since then is this:
- Compiled: January 25 at 18:45 UTC.
- [lt.component:014]: Version: 0.12.3+sha.b10db63 
- Firmware: 2023.1.0-dev.

I tried rolling back the code of esphome-libretuya and the platformio libretuya package to versions from that time, but I couldn't get the platofrmio packages to roll back successfully.

Incidentally, this happened at the same time as Home Assistant gave me notifications about API passwords being deprecated. I switched my configs for all devices to use the API encryption key at that point, and that was when the 5 devices wouldn't accept a new firmware (or at least, that's when I noticed that they weren't updating). But I don't think that's directly the issue, since these 5 devices won't accept new ESPHome firmware even when they're set to keep using an API password instead of API encryption keys.

Here's some of the (hopefully relevant) output from running `build_profile.py` on the dump from the BW942. Seems to be a 1.0.3 bootloader?
```
[+] Matched pattern for BK7231T version SDK 2.0.0 8710_2M, payload type datagram
[+] datagram payload address gadget (THUMB): 0x8F47B
[+] Searching for finish address
[+] Finish address gadget (THUMB): 0x9BFFF
[+] ap_ssid: Merkury
[+] swv: 1.0.3
[+] bv: 30.05
[+] SDK: 2.0.0
[+] Device class: oem_bk7231s_light_ty_oldDp
```

I'm not sure how to check on the bootloader for the Sylvania bulbs, as they're not SmartLife.

**Comment by kuba2k2** [comment]
I've added a fix on March 11, which should fix the OTA issue. Make sure to update LibreTuya in PlatformIO (force update, or uninstall and install) and compile a clean build.

**Comment by marcosrogers** [comment]
It worked on all 5 of my devices that were affected. Thanks!
