### ISSUE TITLE
OTA roll back

### ISSUE THREAD

**Issue by esnet146** [kuba2k2/libretuya#97]
Found a problem with the SM2135 driver. The one that is currently used in esphome does not work correctly. Does not switch modes from RGB to warm-cold. This is not your problem and I'm not asking for a solution. That's just to find out all this, I had to flash the openbeken back to eliminate the hardware malfunction. Remove the light bulb, disassemble, unsolder the board with the chip, connect the uart and flash it.

I ask you to create a file in UF2 format for flashing via OTA to roll back to any version of the openbacker.

P.S. [Old, working version of the driver](https://git.kolosowscy.pl/homeassistant/esphome-hardware/-/tree/10d9f14fe8e9185eab9cc4ed9f239e3e4a0e0203/custom_components/sm2135)

Apparently the new one should contain time delays.

**Comment by kuba2k2** [comment]
The SM2135 driver is probably broken in the upstream ESPHome, but there are working versions which can be imported as a custom component. After compiling such a component, it can be flashed via OTA to the device.

OTA rollback is also possible, provided you have a valid UF2 update file. As I'm not working on, nor using OpenBeken, I'm not going to create files with their firmware. Instead, you can ask the author of OBK to provide UF2 files.

**Comment by esnet146** [comment]
Thanks, with the custom driver everything works fine.
UF2 collect yourself :-(

**Comment by kuba2k2** [comment]
I'm not sure I understand.

**Comment by esnet146** [comment]
[Report](https://www.elektroda.com/rtvforum/raport.php?link=20490588) | Helpful post? (0)
[#5](https://www.elektroda.com/rtvforum/viewtopic.php?p=20490588#20490588) 15 Mar 2023 20:41
for bk7231t -> -f bk7231u

ltchiptool uf2 write -f bk7231u -b generic-bk7231t-qfn32-tuya -o openbkt.uf2 'download;OpenBK7231T_1.15.440.rbl'

ltchiptool uf2 info openbkt.uf2
I: Family: BK7231U / Beken 7231U/7231T
I: Tags:
I: - BOARD: generic-bk7231t-qfn32-tuya
I: - DEVICE_ID: 7b4bd984
I: - BUILD_DATE: bd011264
I: - OTA_VERSION: 01
I: - DEVICE: LibreTuya
I: - LT_HAS_OTA1: 01
I: - LT_HAS_OTA2: 01
I: - LT_PART_1: download
I: - LT_PART_2: download
I: Data chunks: 1868
I: Total binary size: 478016

**Comment by kuba2k2** [comment]
Keep in mind that an UF2 file created this way is only valid for OTA, and will not work for UART flashing (as it will write the OTA image right where the app should be). For a proper OTA package, you should add two semicolons before "download', like `;;download;filename.rbl`.

**Comment by esnet146** [comment]
Thanks!!! New tests will be easier. Without soldering iron.

ltchiptool uf2 write -f bk7231u -b generic-bk7231t-qfn32-tuya -o openbkt.uf2 ';;download;OpenBK7231T_1.15.440.rbl'

I: Family: BK7231U / Beken 7231U/7231T
I: Tags:
I:  - BOARD: generic-bk7231t-qfn32-tuya
I:  - DEVICE_ID: 7b4bd984
I:  - BUILD_DATE: 12ac1264
I:  - OTA_VERSION: 01
I:  - DEVICE: LibreTuya
I:  - LT_HAS_OTA1: 00
I:  - LT_HAS_OTA2: 01
I:  - LT_PART_1: 
I:  - LT_PART_2: download
I: Data chunks: 1868
I: Total binary size: 478016

**Comment by esnet146** [comment]
SM2135:
external_components:
  - source: github://pr#3850
    components: [ sm2135 ]

sm2135:
  data_pin: P8
  clock_pin: P7
  cw_current: 35mA
  rgb_current: 20mA

**Comment by kuba2k2** [comment]
Yes, those are the working components I mentioned before.

**Comment by GrumpyMeow** [comment]
Confirmed that this enables the white leds.... (Y)
